const { Player } = require("../db");

const pick = (array) => {
  var i = Math.floor(Math.random() * array.length);
  return array[i];
};

const createMassivePlayers = async (cantidad) => {
  const playerAvatars = [
    "https://res.cloudinary.com/dy9tey0yi/image/upload/v1637177226/Futbol%20players/cristiano-ronaldo_zm5u9x.png",
    "https://res.cloudinary.com/dy9tey0yi/image/upload/v1637177222/Futbol%20players/griezmann_vuq91e.png",
    "https://res.cloudinary.com/dy9tey0yi/image/upload/v1637177218/Futbol%20players/harry-kane_aiihom.png",
    "https://res.cloudinary.com/dy9tey0yi/image/upload/v1637177216/Futbol%20players/isco-alarcon_sg4oyg.png",
    "https://res.cloudinary.com/dy9tey0yi/image/upload/v1637177211/Futbol%20players/luis-suarez_hgaslb.png",
    "https://res.cloudinary.com/dy9tey0yi/image/upload/v1637177208/Futbol%20players/luka-modric_zx9gzn.png",
    "https://res.cloudinary.com/dy9tey0yi/image/upload/v1637177204/Futbol%20players/lukaku_jvomvt.png",
    "https://res.cloudinary.com/dy9tey0yi/image/upload/v1637177198/Futbol%20players/mbappe-1_cstw3v.png",
    "https://res.cloudinary.com/dy9tey0yi/image/upload/v1637177194/Futbol%20players/messi_smr35u.png",
    "https://res.cloudinary.com/dy9tey0yi/image/upload/v1637177188/Futbol%20players/mo-salah_uzsqpz.png",
    "https://res.cloudinary.com/dy9tey0yi/image/upload/v1637177184/Futbol%20players/neymar_blhysd.png",
    "https://res.cloudinary.com/dy9tey0yi/image/upload/v1637177180/Futbol%20players/paul-pogba_d4zls8.png",
    "https://res.cloudinary.com/dy9tey0yi/image/upload/v1637177176/Futbol%20players/ramadel-falcao_ityyun.png",
    "https://res.cloudinary.com/dy9tey0yi/image/upload/v1637177170/Futbol%20players/sergio-ramos_caea4j.png",
    "https://res.cloudinary.com/dy9tey0yi/image/upload/v1637177147/Futbol%20players/toni-kroos_bdjgub.png",
  ];

  const playerStatus = ["oro", "plata", "bronce"];

  const beg = [
    "bs",
    "bu",
    "ca",
    "ki",
    "ch",
    "di",
    "fa",
    "ph",
    "gu",
    "gh",
    "hu",
    "wh",
    "ja",
    "ge",
    "lo",
    "ma",
    "gn",
    "kn",
    "pn",
    "pi",
    "ra",
    "rh",
    "wr",
    "sa",
    "ci",
    "ps",
    "pt",
    "va",
    "wi",
    "wh",
    "ye",
    "zi",
    "x",
    "zh",
    "ch",
    "th",
    "au",
    "ae",
    "e",
    "i",
    "eur",
    "qu",
    "yew",
    "u",
    "aur",
    "gui",
    "fran",
    "a",
    "pa",
    "fer",
  ];

  const mid = [
    "cu",
    "qu",
    "ji",
    "he",
    "gi",
    "i",
    "n",
    "si",
    "z",
    "cc",
    "tch",
    "ce",
    "ci",
    "ti",
    "ai",
    "ay",
    "ea",
    "ei",
    "ie",
    "ee",
    "ei",
    "ie",
    "ui",
    "y",
    "eau",
    "ough",
    "o",
    "oe",
    "oo",
    "ou",
    "u",
    "aigh",
    "au",
    "ay",
    "ea",
    "ix",
    "eau",
    "yr",
    "ir",
    "eir",
    "er",
    "gui",
    "di",
    "qui",
    "le",
    "seado",
    "nan",
  ];

  const end = [
    "ck",
    "ed",
    "gue",
    "due",
    "mb",
    "mn",
    "bt",
    "s",
    "ng",
    "ge",
    "ch",
    "tch",
    "sh",
    "th",
    "x",
    "ew",
    "ut",
    "iew",
    "ier",
    "ear",
    "eer",
    "eir",
    "air",
    "oar",
    "oor",
    "our",
    "ar",
    "rei",
    "man",
    "do",
    "to",
    "xito",
    "res",
    "da",
  ];

  for (let i = 1; i <= cantidad; i++) {
    await Player.create({
      status: playerStatus[Math.floor(Math.random() * playerStatus.length)],
      avatar: playerAvatars[Math.floor(Math.random() * playerAvatars.length)],
      ranking: i,
      nickname:
        pick(beg) + pick(mid) + pick(end) + Math.floor(Math.random() * 3000),
    });
  }
  return Promise.resolve();
};


module.exports = createMassivePlayers;