export const GET_ALL_PLAYERS = 'GET_ALL_PLAYERS'
export const GET_BY_ID = 'GET_BY_ID'
export const GET_TOP_TEN = 'GET_TOP_TEN'
export const GET_FEAT = 'GET_FEAT'
export const RESET_DETAIL = 'RESET_DETAIL'